server:
  port: 8000

spring:
  application:
    name: gateway
  config:
    import: "optional:consul:"
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/child, /child/**, /parent, /parent/**
        - id: chores
          uri: lb://chores
          predicates:
            - Path=/chore, /chore/**
        - id: childChore
          uri: lb://childChore
          predicates:
            - Path=/childchore, /childchore/**
