version: "3.8"

services:
  rabbitmq-dev:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - micro_chores

  consul-dev:
    image: consul:1.15.0
    container_name: consul
    ports:
      - '8500:8500'
    command: 'agent -dev -node=chores -client=0.0.0.0 -log-level=INFO'
    networks:
      - micro_chores

  consul-importer:
    image: consul-importer:1.15.0
    depends_on:
      - consul-dev
    networks:
      - micro_chores

networks:
  micro_chores:
    driver: bridge
